enum
{
    IDS_BRICKGENERATOR = 10000,
    ID_BRICKGENERATOR = 1069999,

    BRICKGENERATOR_WIDTH = 1001,
    BRICKGENERATOR_DEPTH = 1002,
    BRICKGENERATOR_HEIGHT = 1003,
    BRICKGENERATOR_QUALITY = 1004,
    BRICKGENERATOR_TYPE = 1005,

    BRICKGENERATOR_ENABLE_LOGO = 1006,
    BRICKGENERATOR_LOGO_SOURCE = 1007,
    BRICKGENERATOR_LOGO_DIAMETER = 1009,
    BRICKGENERATOR_LOGO_HEIGHT = 1010,
    BRICKGENERATOR_GROUP_LOGO = 1011,
    BRICKGENERATOR_LOGO_ROTATION = 1012,
    BRICKGENERATOR_LOGO_BLEND = 1013,
    BRICKGENERATOR_LOGO_SINK = 1014,

    BRICKGENERATOR_QUALITY_DRAFT = 0,
    BRICKGENERATOR_QUALITY_STANDARD = 1,
    BRICKGENERATOR_QUALITY_HERO = 2,
    BRICKGENERATOR_QUALITY_PROXY = 3,

    BRICKGENERATOR_TYPE_BRICK = 0,
    BRICKGENERATOR_TYPE_PLATE = 1
};
