enum
{
    IDS_BRICKGENERATOR = 10000,
    ID_BRICKGENERATOR = 1069999,

    BRICKGENERATOR_WIDTH = 1001,
    BRICKGENERATOR_DEPTH = 1002,
    BRICKGENERATOR_HEIGHT = 1003,
    BRICKGENERATOR_QUALITY = 1004,
    BRICKGENERATOR_TYPE = 1005,

    BRICKGENERATOR_QUALITY_DRAFT = 0,
    BRICKGENERATOR_QUALITY_STANDARD = 1,
    BRICKGENERATOR_QUALITY_HERO = 2,

    BRICKGENERATOR_TYPE_BRICK = 0,
    BRICKGENERATOR_TYPE_PLATE = 1
};
