IDS_BRICKGENERATOR = "Brick"
ID_BRICKGENERATOR = 1069999

BRICKGENERATOR_WIDTH = 1001
BRICKGENERATOR_DEPTH = 1002
BRICKGENERATOR_HEIGHT = 1003
BRICKGENERATOR_QUALITY = 1004
BRICKGENERATOR_TYPE = 1005

BRICKGENERATOR_ENABLE_LOGO = 1006
BRICKGENERATOR_LOGO_SOURCE = 1007
BRICKGENERATOR_LOGO_DIAMETER = 1009
BRICKGENERATOR_LOGO_HEIGHT = 1010
BRICKGENERATOR_GROUP_LOGO = 1011
BRICKGENERATOR_LOGO_ROTATION = 1012
BRICKGENERATOR_LOGO_BLEND = 1013
BRICKGENERATOR_LOGO_SINK = 1014

BRICKGENERATOR_LOGO_ROTATION_0 = 0
BRICKGENERATOR_LOGO_ROTATION_90 = 1
BRICKGENERATOR_LOGO_ROTATION_180 = 2
BRICKGENERATOR_LOGO_ROTATION_270 = 3

BRICKGENERATOR_QUALITY_DRAFT = 0
BRICKGENERATOR_QUALITY_STANDARD = 1
BRICKGENERATOR_QUALITY_HERO = 2

BRICKGENERATOR_TYPE_BRICK = 0
BRICKGENERATOR_TYPE_PLATE = 1


# ---------------------------------------------------------------------
# BrickIt — mesh -> brick assembly generator
# ---------------------------------------------------------------------
IDS_BRICKIFYASSEMBLY = "BrickIt"
ID_BRICKIFYASSEMBLY = 1069998
IDS_BRICKLIBRARYPANEL = "Brick Panel"
ID_BRICKLIBRARYPANEL = 1069997
ID_BRICKIT_EFFECTORS_AUTOHOOK = 1069995

BRICKIFYASSEMBLY_SOURCE = 2001
BRICKIFYASSEMBLY_STUDS_ACROSS = 2002
BRICKIFYASSEMBLY_VOXEL_MODE = 2003
BRICKIFYASSEMBLY_QUALITY = 2004
BRICKIFYASSEMBLY_MERGE_PLATES = 2005
BRICKIFYASSEMBLY_PRUNE_CONNECTIVITY = 2006
BRICKIFYASSEMBLY_MAX_BRICK_HEIGHT = 2008
BRICKIFYASSEMBLY_REBUILD = 2009
BRICKIFYASSEMBLY_CLEANUP_PROTRUSIONS = 2010
BRICKIFYASSEMBLY_SHELL_THICKNESS = 2011
BRICKIFYASSEMBLY_USE_MANUAL_STUD_SIZE = 2012
BRICKIFYASSEMBLY_STUD_SIZE = 2013
BRICKIFYASSEMBLY_DETAIL_MODE = 2014
BRICKIFYASSEMBLY_VISUALIZATION_MODE = 2015
BRICKIFYASSEMBLY_AUTO_REBUILD = 2016
BRICKIFYASSEMBLY_HERO = 2017
BRICKIFYASSEMBLY_VOXEL_RESOLUTION = 2018
BRICKIFYASSEMBLY_LIB_PRESET_ALL = 2019
BRICKIFYASSEMBLY_LIB_PRESET_NONE = 2020
BRICKIFYASSEMBLY_LIB_PRESET_BRICKS = 2021
BRICKIFYASSEMBLY_LIB_PRESET_PLATES = 2022
BRICKIFYASSEMBLY_LIB_PRESET_1X1 = 2023
BRICKIFYASSEMBLY_LIB_PRESET_INVERT = 2024
BRICKIFYASSEMBLY_LIBRARY_COUNT = 2025
BRICKIFYASSEMBLY_HEIGHT_PRESET_FINE = 2026
BRICKIFYASSEMBLY_HEIGHT_PRESET_BALANCED = 2027
BRICKIFYASSEMBLY_HEIGHT_PRESET_BLOCKY = 2028
BRICKIFYASSEMBLY_HEIGHT_VARIATION = 2029
BRICKIFYASSEMBLY_HEIGHT_VARIATION_SEED = 2030
BRICKIFYASSEMBLY_HEIGHT_VARIATION_AMOUNT = 2031
BRICKIFYASSEMBLY_HIDE_SOURCE_MESH = 2032
BRICKIFYASSEMBLY_OPEN_LIBRARY_PICKER = 2033
BRICKIFYASSEMBLY_LIBRARY_MASK = 2034
BRICKIFYASSEMBLY_PRESERVE_TINY_GAPS = 2035
BRICKIFYASSEMBLY_SURFACE_ONLY_PLATES = 2036
BRICKIFYASSEMBLY_ENABLE_PLATES = 2037
BRICKIFYASSEMBLY_VOXEL_BACKEND = 2038
BRICKIFYASSEMBLY_ENABLE_LOGO = 2039
BRICKIFYASSEMBLY_LOGO_ROTATION = 2040
BRICKIFYASSEMBLY_LOGO_DIAMETER = 2041
BRICKIFYASSEMBLY_LOGO_HEIGHT = 2042
BRICKIFYASSEMBLY_LOGO_SOURCE = 2043
BRICKIFYASSEMBLY_BUILD_Y_OFFSET = 2044
BRICKIFYASSEMBLY_LOGO_BLEND = 2045
BRICKIFYASSEMBLY_LOGO_SINK = 2046
BRICKIFYASSEMBLY_BUILD_PROGRESS = 2047
BRICKIFYASSEMBLY_BUILD_STAGGER = 2049

BRICKIFYASSEMBLY_GROUP_HERO = 2050
BRICKIFYASSEMBLY_GROUP_LIBRARY = 2051
BRICKIFYASSEMBLY_GROUP_LIBRARY_GRID = 2052
BRICKIFYASSEMBLY_GROUP_LIBRARY_PRESETS = 2053
BRICKIFYASSEMBLY_GROUP_SOURCE = 2054
BRICKIFYASSEMBLY_GROUP_BUILD_ANIM = 2055
BRICKIFYASSEMBLY_GROUP_VOXEL = 2056
BRICKIFYASSEMBLY_GROUP_BRICK_SELECTION = 2057
BRICKIFYASSEMBLY_GROUP_DISPLAY = 2058
BRICKIFYASSEMBLY_GROUP_ACTIONS = 2059
BRICKIFYASSEMBLY_GROUP_HEIGHT_PRESETS = 2061
BRICKIFYASSEMBLY_GROUP_BRICK_HEIGHT = 2062
BRICKIFYASSEMBLY_GROUP_LIBRARY_THUMBS = 2063
BRICKIFYASSEMBLY_TAB_SHAPE = 2064
BRICKIFYASSEMBLY_TAB_LAYOUT = 2065
BRICKIFYASSEMBLY_TAB_PREVIEW = 2066
BRICKIFYASSEMBLY_GROUP_LOGO = 2067
BRICKIFYASSEMBLY_TAB_MOGRAPH = 2068
BRICKIFYASSEMBLY_TOP_SURFACE_PHASE = 2069
BRICKIFYASSEMBLY_TOP_SURFACE_COVERAGE = 2070
BRICKIFYASSEMBLY_BUILD_MOTION_CURVE = 2071
BRICKIFYASSEMBLY_BUILD_CUSTOM_CURVE = 2072
BRICKIFYASSEMBLY_BUILD_SCALE_IN = 2073
BRICKIFYASSEMBLY_CREATE_PROXY_MOGRAPH = 2074
BRICKIFYASSEMBLY_SWAP_PROXY_RENDER = 2075
BRICKIFYASSEMBLY_BRICK_SEPARATION = 2076
BRICKIFYASSEMBLY_BUILD_SUBTLE_ROTATION = 2077
BRICKIFYASSEMBLY_BUILD_TILT_AMOUNT = 2078
BRICKIFYASSEMBLY_TOP_SURFACE_RANDOM_ORDER = 2079
BRICKIFYASSEMBLY_SPACER_1 = 2080
BRICKIFYASSEMBLY_SPACER_2 = 2081
BRICKIFYASSEMBLY_SPACER_3 = 2082
BRICKIFYASSEMBLY_SPACER_4 = 2083
BRICKIFYASSEMBLY_LABEL_CHOOSE_BRICKS = 2084
BRICKIFYASSEMBLY_TOP_SURFACE_START = 2085
BRICKIFYASSEMBLY_TOP_SURFACE_BLEND = 2086
BRICKIFYASSEMBLY_GROUP_BRICK_ADJUSTMENTS = 2087
BRICKIFYASSEMBLY_HUMANIZE_BRICKS = 2088
BRICKIFYASSEMBLY_HUMANIZE_SEED = 2089
BRICKIFYASSEMBLY_HUMANIZE_POSITION = 2090
BRICKIFYASSEMBLY_HUMANIZE_ROTATION = 2091
BRICKIFYASSEMBLY_MOGRAPH_EFFECTORS = 2093
BRICKIFYASSEMBLY_CREATE_RS_COLOR_MATERIAL = 2094
BRICKIFYASSEMBLY_GROUP_PREVIEW_DEBUG = 2095
BRICKIFYASSEMBLY_BUILD_HANG_TIME = 2096
BRICKIFYASSEMBLY_SMOOTH_TOP_PROGRESS = 2097
BRICKIFYASSEMBLY_GROUP_SETUP = 2098
BRICKIFYASSEMBLY_TAB_EFFECTORS = 2099
BRICKIFYASSEMBLY_CAP_STYLE = 2300
BRICKIFYASSEMBLY_CAP_RANDOM_SEED = 2301

BRICKIFYASSEMBLY_CAP_STYLE_MATCH_BELOW = 0
BRICKIFYASSEMBLY_CAP_STYLE_RANDOM_MIX = 1
BRICKIFYASSEMBLY_CAP_STYLE_MERGED_COVER = 2

ID_BRICK_MOGRAPH_EVALUATOR_TAG = 1070999
MSG_BRICK_MOGRAPH_EVALUATE = 1071999
MSG_BRICK_MOGRAPH_WRITE_CARRIER_MODATA = 1071998

BRICK_MOGRAPH_WRITE_CARRIER = 1100
BRICK_MOGRAPH_WRITE_MATRIX = 1101
BRICK_MOGRAPH_WRITE_COLOR = 1102
BRICK_MOGRAPH_WRITE_OK = 1103
BRICK_MOGRAPH_EVAL_COUNT = 1000
BRICK_MOGRAPH_EVAL_EFFECTORS = 1001
BRICK_MOGRAPH_EVAL_OK = 1002
BRICK_MOGRAPH_EVAL_GENERATOR = 1003
BRICK_MOGRAPH_EVAL_COLOR_CHANGED = 1004
BRICK_MOGRAPH_EVAL_FIELD_COLOR_APPLIED = 1005
BRICK_MOGRAPH_EVAL_FIELD_COLOR_MODE_COUNT = 1006
BRICK_MOGRAPH_EVAL_SKIP_FIELD_OVERRIDE = 1007
BRICK_MOGRAPH_EVAL_EFFECTOR_COLOR_CHANGED = 1008
BRICK_MOGRAPH_EVAL_POST_FIELD_COLOR_CHANGED = 1009
BRICK_MOGRAPH_EVAL_MANUAL_FIELD_SKIPPED = 1010
BRICK_MOGRAPH_EVAL_SAMPLE_COUNT = 1011
BRICK_MOGRAPH_EVAL_IN_MATRIX_BASE = 200000
BRICK_MOGRAPH_EVAL_IN_COLOR_BASE = 300000
BRICK_MOGRAPH_EVAL_OUT_MATRIX_BASE = 400000
BRICK_MOGRAPH_EVAL_OUT_COLOR_BASE = 500000
BRICK_MOGRAPH_EVAL_EFFECTOR_COLOR_SAMPLE_BASE = 600000
BRICK_MOGRAPH_EVAL_FIELD_COLOR_SAMPLE_BASE = 601000

# 15 brick library toggles (DEFAULT_LIBRARY order). The brick pipeline
# library list is the ordered source-of-truth; index into that list with
# (brick_id - BRICKIFYASSEMBLY_BRICK_BASE).
BRICKIFYASSEMBLY_BRICK_BASE = 2100
BRICKIFYASSEMBLY_BRICK_BRICK_1X1 = 2100
BRICKIFYASSEMBLY_BRICK_BRICK_1X2 = 2101
BRICKIFYASSEMBLY_BRICK_BRICK_1X3 = 2102
BRICKIFYASSEMBLY_BRICK_BRICK_1X4 = 2103
BRICKIFYASSEMBLY_BRICK_BRICK_1X6 = 2104
BRICKIFYASSEMBLY_BRICK_BRICK_1X8 = 2105
BRICKIFYASSEMBLY_BRICK_BRICK_2X2 = 2106
BRICKIFYASSEMBLY_BRICK_BRICK_2X3 = 2107
BRICKIFYASSEMBLY_BRICK_BRICK_2X4 = 2108
BRICKIFYASSEMBLY_BRICK_BRICK_2X6 = 2109
BRICKIFYASSEMBLY_BRICK_BRICK_2X8 = 2110
BRICKIFYASSEMBLY_BRICK_BRICK_3X3 = 2111
BRICKIFYASSEMBLY_BRICK_BRICK_3X4 = 2112
BRICKIFYASSEMBLY_BRICK_BRICK_3X6 = 2113
BRICKIFYASSEMBLY_BRICK_BRICK_3X8 = 2114

BRICKIFYASSEMBLY_THUMB_BASE = 2200
BRICKIFYASSEMBLY_THUMB_BRICK_1X1 = 2200
BRICKIFYASSEMBLY_THUMB_BRICK_1X2 = 2201
BRICKIFYASSEMBLY_THUMB_BRICK_1X3 = 2202
BRICKIFYASSEMBLY_THUMB_BRICK_1X4 = 2203
BRICKIFYASSEMBLY_THUMB_BRICK_1X6 = 2204
BRICKIFYASSEMBLY_THUMB_BRICK_1X8 = 2205
BRICKIFYASSEMBLY_THUMB_BRICK_2X2 = 2206
BRICKIFYASSEMBLY_THUMB_BRICK_2X3 = 2207
BRICKIFYASSEMBLY_THUMB_BRICK_2X4 = 2208
BRICKIFYASSEMBLY_THUMB_BRICK_2X6 = 2209
BRICKIFYASSEMBLY_THUMB_BRICK_2X8 = 2210
BRICKIFYASSEMBLY_THUMB_BRICK_3X3 = 2211
BRICKIFYASSEMBLY_THUMB_BRICK_3X4 = 2212
BRICKIFYASSEMBLY_THUMB_BRICK_3X6 = 2213
BRICKIFYASSEMBLY_THUMB_BRICK_3X8 = 2214

BRICKIFYASSEMBLY_VOXEL_MODE_SOLID = 0
BRICKIFYASSEMBLY_VOXEL_MODE_SHELL = 1

BRICKIFYASSEMBLY_VOXEL_BACKEND_INTERNAL = 0
BRICKIFYASSEMBLY_VOXEL_BACKEND_C4D_VOLUME = 1

BRICKIFYASSEMBLY_QUALITY_DRAFT = 0
BRICKIFYASSEMBLY_QUALITY_STANDARD = 1
BRICKIFYASSEMBLY_QUALITY_HERO = 2
BRICKIFYASSEMBLY_QUALITY_PROXY = 3

BRICKIFYASSEMBLY_DETAIL_MODE_OFF = 0
BRICKIFYASSEMBLY_DETAIL_MODE_BALANCED = 1
BRICKIFYASSEMBLY_DETAIL_MODE_PRESERVE = 2

BRICKIFYASSEMBLY_VISUALIZATION_MODE_SOURCE = 0
BRICKIFYASSEMBLY_VISUALIZATION_MODE_BRICK_SIZE = 1
BRICKIFYASSEMBLY_VISUALIZATION_MODE_SHELL_DEPTH = 2
BRICKIFYASSEMBLY_VISUALIZATION_MODE_SHELL_WIREFRAME = 3
BRICKIFYASSEMBLY_VISUALIZATION_MODE_VOXEL_DEBUG = 4

BRICKIFYASSEMBLY_LOGO_ROTATION_0 = 0
BRICKIFYASSEMBLY_LOGO_ROTATION_90 = 1
BRICKIFYASSEMBLY_LOGO_ROTATION_180 = 2
BRICKIFYASSEMBLY_LOGO_ROTATION_270 = 3

BRICKIFYASSEMBLY_BUILD_MOTION_CURVE_EASE = 0
BRICKIFYASSEMBLY_BUILD_MOTION_CURVE_EASE_IN = 1
BRICKIFYASSEMBLY_BUILD_MOTION_CURVE_EASE_OUT = 2
BRICKIFYASSEMBLY_BUILD_MOTION_CURVE_SPRING = 3
BRICKIFYASSEMBLY_BUILD_MOTION_CURVE_SLAM = 4
BRICKIFYASSEMBLY_BUILD_MOTION_CURVE_QUADRATIC = 5
BRICKIFYASSEMBLY_BUILD_MOTION_CURVE_CUSTOM = 6
BRICKIFYASSEMBLY_BUILD_MOTION_CURVE_BOUNCE = 7

# Registered icons (must match obrickifyassembly.h)
ICON_BRICKIFY_HERO = 1090000
ICON_BRICKIFY_BRICK_BASE = 1090100
