enum
{
    BRICKGENERATOR = 1000,
    BRICKGENERATOR_WIDTH = 1001,
    BRICKGENERATOR_DEPTH = 1002,
    BRICKGENERATOR_HEIGHT = 1003,
    BRICKGENERATOR_QUALITY = 1004,

    BRICKGENERATOR_QUALITY_DRAFT = 0,
    BRICKGENERATOR_QUALITY_STANDARD = 1,
    BRICKGENERATOR_QUALITY_HERO = 2
};
