#ifndef _Tbrickitfollowsurface_H_
#define _Tbrickitfollowsurface_H_

enum
{
    BRICKIT_FOLLOW_SURFACE_ENABLED = 2000,
    BRICKIT_FOLLOW_SURFACE_SOURCE = 2001,
    BRICKIT_FOLLOW_SURFACE_RECORDS = 2002,
    BRICKIT_FOLLOW_SURFACE_ORIENT_MODE = 2003,
    BRICKIT_FOLLOW_SURFACE_ORIENT_SMOOTHING = 2004,
    BRICKIT_FOLLOW_SURFACE_BAKE_BUTTON = 2005,
    BRICKIT_FOLLOW_SURFACE_SWAP_HERO_BUTTON = 2006,
    BRICKIT_FOLLOW_SURFACE_BRICKIT_OP = 2007,
    BRICKIT_FOLLOW_SURFACE_SWAP_QUALITY = 2008,
    BRICKIT_FOLLOW_SURFACE_ORIENT_WORLD_UP = 0,
    BRICKIT_FOLLOW_SURFACE_ORIENT_FOLLOW_NORMAL = 1,
    BRICKIT_FOLLOW_SURFACE_SWAP_QUALITY_DRAFT = 0,
    BRICKIT_FOLLOW_SURFACE_SWAP_QUALITY_STANDARD = 1,
    BRICKIT_FOLLOW_SURFACE_SWAP_QUALITY_HERO = 2
};

#endif
